Import ASUSWRT-MERLIN_384.3
Change-Id: Idd65bc5af2e223095cab38a8ea1cdf2bff0993d6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2169,17 +2169,17 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   (exit $ac_status); }; }; then
     cross_compiling=no
   else
-    if test "$cross_compiling" = maybe; then
+#    if test "$cross_compiling" = maybe; then
 	cross_compiling=yes
-    else
-	{ { echo "$as_me:$LINENO: error: cannot run C compiled programs.
-If you meant to cross compile, use \`--host'.
-See \`config.log' for more details." >&5
-echo "$as_me: error: cannot run C compiled programs.
-If you meant to cross compile, use \`--host'.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-    fi
+#    else
+#	{ { echo "$as_me:$LINENO: error: cannot run C compiled programs.
+#If you meant to cross compile, use \`--host'.
+#See \`config.log' for more details." >&5
+#echo "$as_me: error: cannot run C compiled programs.
+#If you meant to cross compile, use \`--host'.
+#See \`config.log' for more details." >&2;}
+#   { (exit 1); exit 1; }; }
+#    fi
   fi
 fi
 { echo "$as_me:$LINENO: result: yes" >&5
@@ -5263,9 +5263,9 @@ _ACEOF
 esac
 
 
-cat >>confdefs.h <<\_ACEOF
+#cat >>confdefs.h <<\_ACEOF
 #define malloc rpl_malloc
-_ACEOF
+#_ACEOF
 
 fi
 
@@ -7210,7 +7210,7 @@ do
     cat >>$CONFIG_STATUS <<_ACEOF
     # First, check the format of the line:
     cat >"\$tmp/defines.sed" <<\\CEOF
-/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*/b def
+/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*\$/b def
 /^[	 ]*#[	 ]*define[	 ][	 ]*$ac_word_re[(	 ]/b def
 b
 :def
